ARG NODE_VERSION=24.14.0-slim

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install


COPY . .

ENV WATCHPACK_POLLING=true

ENV HOSTNAME="0.0.0.0"


EXPOSE 3000


CMD ["npm", "run", "dev"]