from __future__ import annotations
from sqlalchemy import Integer, BIGINT, Text, ForeignKey, DateTime, Date, Time
from sqlalchemy.orm import Mapped, mapped_column, relationship
from ..db.base import BaseModel
from typing import TYPE_CHECKING, List
from geoalchemy2 import Geometry, WKBElement
from sqlalchemy import func
from datetime import datetime, time, date, timezone
from sqlalchemy.dialects.postgresql import UUID
if TYPE_CHECKING:
    from .users import Users


# COMPLAINTS MODEL
class Complaints(BaseModel):
    """
    Complaints Model This Table/Model collect consumers complaints regarding 
    Distribution utily, meters, or other that affect consumer Electricity

    #### Column:
    
        - id:int = Primary Key of this Table
        - user_id:int = The Foreignkey of this table related to users_account TABLE.
        - subject:str = The Subject/Title of the Complaints Report
        - description:str = The description and Information of Complaints Report
        - reference_pole:str = The reference Pole where the Complaints are nearest 
        or for meter Complaint the Reference Pole where the meter is connected.
        - location:Geometry = Geometry Point where the complaints must be done.
        - village:str = Autogenerated Column by trigger when locations is not null
        - municipality:str = Autogenerated Column by tigger when locations is not null
        - date:str = Date complained
        - time_started:str = Time When the Problem occur
        - time_complete:str = Time when the Problem or Complaint occur
        - status:str = Status of Complaints (eg. Receive, Working, Complete)
        - remarks:str = Addional Remarks or Informartion on Complaints.  
    """
    __tablename__ = "consumer_complaints"
    id:Mapped[int] = mapped_column(type_=Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users_account.id", ondelete="CASCADE", onupdate="CASCADE"), type_=UUID())
    subject: Mapped[str] = mapped_column(type_=Text, nullable=True)
    description: Mapped[str] = mapped_column(type_=Text, nullable=True)
    reference_pole: Mapped[str] = mapped_column(type_=Text)
    location: Mapped[WKBElement] = mapped_column(type_=Geometry(geometry_type="POINT", srid=4326), nullable=True)
    village: Mapped[str] = mapped_column(type_=Text)
    municipality: Mapped[str] = mapped_column(type_=Text)
    remarks: Mapped[str] = mapped_column(type_=Text, nullable=True)
    time_stamped: Mapped[datetime] = mapped_column(type_=DateTime(timezone=True), nullable=True, default=func.now())
    
    # relationships
    user: Mapped["Users"] = relationship(back_populates="complaints")
    complaints_image: Mapped[List["ComplaintsImage"]] = relationship(back_populates="complaints")
    completed_images: Mapped[List["ComplaintsImageCompleted"]] = relationship(back_populates="complaints")
    status_updates: Mapped[List["ComplaintsStatusUpdates"]] = relationship(
        back_populates="complaints",
        cascade="all, delete-orphan",
        order_by="ComplaintsStatusUpdates.date, ComplaintsStatusUpdates.time")


# COMPLAINTS STATUS NAME TABLE 
class ComplaintsStatusName(BaseModel):
    __tablename__ = "complaints_status_name"
    id:Mapped[int] = mapped_column(type_=Integer, primary_key=True)
    status_name:Mapped[str] = mapped_column(type_=Text, unique=True)
    description:Mapped[str] = mapped_column(type_=Text, nullable=True)
    # relationships
    status_updates: Mapped[List["ComplaintsStatusUpdates"]] = relationship(
        back_populates="status")
   
class ComplaintsStatusUpdates(BaseModel):
    __tablename__ = "complaints_status"
    id:Mapped[int] = mapped_column(type_=Integer, primary_key=True)
    complaint_id: Mapped[int] = mapped_column(
        ForeignKey("consumer_complaints.id", ondelete="CASCADE", onupdate="CASCADE"),
        type_=Integer)
    status_id: Mapped[int] = mapped_column(
        ForeignKey("complaints_status_name.id", ondelete="CASCADE", onupdate="CASCADE"),
        type_=Integer)
    date: Mapped[date] = mapped_column(type_=Date)
    time: Mapped[time] = mapped_column(type_=Time)
    # relationships
    complaints: Mapped["Complaints"] = relationship(back_populates="status_updates")
    status: Mapped["ComplaintsStatusName"] = relationship(back_populates="status_updates")

class ComplaintsImage(BaseModel):
    __tablename__ = "complaints_images"
    id:Mapped[int] = mapped_column(type_=Integer, primary_key=True)
    complaints_id: Mapped[int]  = mapped_column(ForeignKey("consumer_complaints.id"), type_=Integer)
    uploaded_at: Mapped[datetime] = mapped_column(type_=DateTime(timezone=True))
    image_url:Mapped[str] = mapped_column(type_=Text, nullable=True)
    
    # relationships
    complaints: Mapped["Complaints"] = relationship(back_populates="complaints_image")
    
class ComplaintsImageCompleted(BaseModel):
    __tablename__ = "completed_complaint_image"
    id:Mapped[int] = mapped_column(type_=Integer, primary_key=True)
    complaint_id: Mapped[int] = mapped_column(ForeignKey("consumer_complaints.id"), type_=Integer)
    image_url: Mapped[str] = mapped_column(type_=Text, nullable=True)
    # relationships
    complaints: Mapped["Complaints"] = relationship(back_populates="completed_images")