from __future__ import annotations
from sqlalchemy import Integer, BIGINT, Text, ForeignKey, DateTime, Date, Time, Boolean
from sqlalchemy.orm import Mapped, mapped_column, relationship
from ....db.base import BaseModel
from typing import TYPE_CHECKING, List
from geoalchemy2 import Geometry, WKBElement
from sqlalchemy import func
from datetime import datetime, time, date, timezone
from sqlalchemy.dialects.postgresql import UUID
if TYPE_CHECKING:
    from ...user.model.users import Users
    from .status_update import ComplaintsStatusUpdates
    from .complaint_image import ComplaintsImage
    from .complete_image import ComplaintsImageCompleted
    from .complaints_history import  ComplaintsStatusHistory
    from .complaints_message import ComplaintsMessage
# COMPLAINTS MODEL
class Complaints(BaseModel):
    """
    Complaints Model This Table/Model collect consumers complaints regarding 
    Distribution utily, meters, or other that affect consumer Electricity

    #### Column:
    
        - id:int = Primary Key of this Table
        - user_id:int = The Foreignkey of this table related to users_account TABLE.
        - subject:str = The Subject/Title of the Complaints Report
        - description:str = The description and Information of Complaints Report
        - reference_pole:str = The reference Pole where the Complaints are nearest 
        or for meter Complaint the Reference Pole where the meter is connected.
        - location:Geometry = Geometry Point where the complaints must be done.
        - village:str = Autogenerated Column by trigger when locations is not null
        - municipality:str = Autogenerated Column by tigger when locations is not null
        - date:str = Date complained
        - time_started:str = Time When the Problem occur
        - time_complete:str = Time when the Problem or Complaint occur
        - status:str = Status of Complaints (eg. Receive, Working, Complete)
        - remarks:str = Addional Remarks or Informartion on Complaints.  
    """
    __tablename__ = "consumer_complaints"
    id:Mapped[int] = mapped_column(type_=Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users_account.id", ondelete="CASCADE", onupdate="CASCADE"), type_=UUID())
    subject: Mapped[str] = mapped_column(type_=Text, nullable=True)
    description: Mapped[str] = mapped_column(type_=Text, nullable=True)
    reference_pole: Mapped[str] = mapped_column(type_=Text)
    location: Mapped[WKBElement] = mapped_column(type_=Geometry(geometry_type="POINT", srid=4326), nullable=True)
    village: Mapped[str] = mapped_column(type_=Text)
    municipality: Mapped[str] = mapped_column(type_=Text)
    remarks: Mapped[str] = mapped_column(type_=Text, nullable=True)
    timestamped: Mapped[datetime] = mapped_column(type_=DateTime(timezone=True), nullable=True, default=func.now())
    is_deleted: Mapped[bool] = mapped_column(type_=Boolean, default=False)
    deleted_at: Mapped[bool] = mapped_column(type_=DateTime(timezone=True), nullable=True)
    
    # relationships
    user: Mapped["Users"] = relationship(back_populates="complaints")
    complaints_image: Mapped[List["ComplaintsImage"]] = relationship(back_populates="complaints")
    completed_images: Mapped[List["ComplaintsImageCompleted"]] = relationship(back_populates="complaints")
    status_updates: Mapped[List["ComplaintsStatusUpdates"]] = relationship(
        back_populates="complaints",
        order_by="ComplaintsStatusUpdates.date, ComplaintsStatusUpdates.time")
    status_history: Mapped[List["ComplaintsStatusHistory"]] = relationship(back_populates="complaint", order_by="ComplaintsStatusHistory.timestamped.desc()")
    complaint_messages: Mapped[List["ComplaintsMessage"]] = relationship(back_populates="complaints")


    
