import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLandingPageData } from "./services/serverapi";
import DocNavigation from "./components/doc";
import Drawer from "./components/drawer";
import ThemeController from "./components/themeController";
const baseurl = process.env.BASESERVERURL
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
 {
  const data = await getLandingPageData()
  return (
    <html lang="en" className="scroll-smooth">
      <ThemeController/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Drawer baseurl={baseurl} title={data.hero.title}>
            {children}
            <DocNavigation/>
         </Drawer>
        
      </body>
    </html>
  );
}
