import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLandingPageData } from "../lib/serverFetch";
import DocNavigation from "./common/doc";
import Drawer from "./common/drawer";
import ThemeController from "./common/themeController";
import { WebsocketProvider } from "./utils/websocketprovider";
import { AuthProvider } from "./utils/authProvider";
import { getCurrentUser } from "../lib/serverFetch";
import { GoogleOAuthProvider } from "@react-oauth/google";


const baseurl = process.env.BASESERVERURL
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getLandingPageData()
  const user = await getCurrentUser()
  const googleClient = process.env.GOOGLE_CLIENT_ID
  return (
    <html lang="en" data-scroll-behavior="smooth" className="scroll-smooth">
      <AuthProvider initialUser={user.status === 200 ? user.detail : null}>
        <GoogleOAuthProvider clientId={googleClient ?? ""}>
          <WebsocketProvider>
            <ThemeController />
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased `}
            >
              <Drawer baseurl={baseurl} title={data.hero.title}>
                {children}
                <DocNavigation />
              </Drawer>
            </body>
          </WebsocketProvider>
        </GoogleOAuthProvider>
      </AuthProvider>
    </html>
  );
}
