"""Consumer Service Drop

Revision ID: 035adedc9f9c
Revises: a6d6404f0ca6
Create Date: 2026-03-10 08:48:47.188056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '035adedc9f9c'
down_revision: Union[str, Sequence[str], None] = 'a6d6404f0ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_drop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('service_drop_id', sa.Text(), nullable=False),
    sa.Column('from_bus_id', sa.Text(), nullable=False),
    sa.Column('to_customer_id', sa.Text(), nullable=False),
    sa.Column('phasing', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('length_meters_1', sa.Numeric(precision=10, scale=4), sa.Computed('ST_LENGTH(geom::geography)', ), nullable=True),
    sa.Column('length_meters_2', sa.Numeric(precision=10, scale=4), sa.Computed('30', ), nullable=True),
    sa.Column('conductor_type', sa.Integer(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True), 
    sa.ForeignKeyConstraint(['conductor_type'], ['gis.conductor_wires.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_bus_id'], ['gis.bus.bus_id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['gis.municipality.id'], ),
    sa.ForeignKeyConstraint(['to_customer_id'], ['gis.consumer_meter.account_no'], ),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_drop_id'),
    sa.UniqueConstraint('to_customer_id'),
    schema='gis'
    )
    op.create_index('idx_service_drop_geom', 'service_drop', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)
    
    
    # ### TRIGGERS ###
    op.execute("""
               CREATE OR REPLACE FUNCTION service_drop_trigger_func()
               RETURNS TRIGGER AS $$
               DECLARE
               service_drop_id text;
               from_bus_id text;
               to_customer_id text;
               phasing text;
               village_id integer;
               municipal_id integer;
               BEGIN
                    IF NEW.description ILIKE '%PRIMARY%' THEN
                        IF EXISTS(SELECT 1 FROM gis.distribution_transformer as dt1 where st_intersects(dt1.geom, ST_STARTPOINT(NEW.geom))) THEN
                            SELECT dt.from_primary_bus_id, dt.primary_phasing
                            INTO from_bus_id, phasing
                            FROM gis.distribution_transformer as dt
                            where st_intersects(dt.geom, ST_STARTPOINT(NEW.geom))
                            LIMIT 1;
                        ELSE 
                            SELECT b.bus_id, pl.phasing
                            INTO from_bus_id, phasing
                            FROM gis.bus as b
                            JOIN gis.primary_lines as pl on pl.to_bus_id = b.bus_id
                            WHERE ST_INTERSECTS(b.geom, ST_STARTPOINT(NEW.geom))
                            AND b.description ILIKE '%PRIMARY%'
                            LIMIT 1;
                        END IF;
                    ELSE
                        IF EXISTS(SELECT 1 FROM gis.transformer_linebushing as tl where ST_INTERSECTS(ST_ENDPOINT(tl.geom), ST_STARTPOINT(NEW.geom))) THEN
                            SELECT b.bus_id, dt.secondary_phasing
                            INTO from_bus_id, phasing
                            FROM gis.bus as b
                            JOIN gis.distribution_transformer as dt on dt.to_secondary_bus_id = b.bus_id
                            WHERE  ST_INTERSECTS(b.geom, ST_STARTPOINT(NEW.geom))
                            LIMIT 1;
                        ELSE 
                            SELECT b.bus_id, sl.phasing
                            INTO from_bus_id, phasing
                            FROM gis.bus as b
                            JOIN gis.secondary_lines as sl on sl.to_bus_id = b.bus_id
                            WHERE ST_INTERSECTS(b.geom, ST_STARTPOINT(NEW.geom))
                            LIMIT 1;
                        END IF;
                    END IF;
                    
                    SELECT 'SD' || cons.account_no, cons.account_no, cons.village_id, cons.municipality_id
                    INTO service_drop_id, to_customer_id, village_id, municipal_id
                    FROM gis.consumer_meter as cons
                    WHERE ST_INTERSECTS(cons.geom, ST_ENDPOINT(NEW.geom))
                    LIMIT 1;
                    
                    IF from_bus_id IS NULL OR to_customer_id IS NULL or service_drop_id IS NULL THEN
                        RAISE EXCEPTION 'Service Drop not found Please Correct Line Geometry';
                    END IF;
                
                NEW.service_drop_id = service_drop_id;
                NEW.from_bus_id = from_bus_id;
                NEW.to_customer_id = to_customer_id;
                NEW.phasing = phasing;
                NEW.village_id = village_id;
                NEW.municipality_id = municipal_id;
                RETURN NEW;
               END;
               $$
               LANGUAGE 'plpgsql';
               """)
    
    op.execute("""
               CREATE TRIGGER service_drop_trigger
               BEFORE INSERT OR UPDATE
               ON gis.service_drop
               FOR EACH ROW EXECUTE PROCEDURE service_drop_trigger_func();
               """)
    
    # AFTER TRIGGER
    op.execute("""
               CREATE OR REPLACE FUNCTION service_drop_trigger_after_func()
               RETURNS TRIGGER AS $$
               BEGIN
                    -- UPDATE CONSUMER
                    UPDATE gis.consumer_meter as cons
                    SET is_active = new.is_active
                    where cons.account_no = new.to_customer_id
                    AND cons.is_active is distinct from new.is_active;
                    RETURN NEW;
               END;
               $$ LANGUAGE plpgsql;
               """)
    op.execute("""
               CREATE TRIGGER service_drop_trigger_after
               AFTER INSERT OR UPDATE
               ON gis.service_drop
               FOR EACH ROW EXECUTE PROCEDURE service_drop_trigger_after_func();
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_service_drop_geom', table_name='service_drop', schema='gis', postgresql_using='gist', if_exists=True)
    op.drop_table('service_drop', schema='gis')
    # ### end Alembic commands ###
