"""complaints_message_and_history

Revision ID: 1189dc695fda
Revises: 035adedc9f9c
Create Date: 2026-03-29 04:25:30.013623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '1189dc695fda'
down_revision: Union[str, Sequence[str], None] = '035adedc9f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Complaints History
    op.create_table('complaints_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaints_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_pole', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complaints_id'], ['consumer_complaints.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_complaints_history_location', 'complaints_history', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
    # Complaint Message
    op.create_table('complaints_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaints_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaints_id'], ['consumer_complaints.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users_account.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['consumer_complaints.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['complaints_status_name.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('complaints_status_history')
    op.drop_table('complaints_message')
    op.drop_index('idx_complaints_history_location', table_name='complaints_history', postgresql_using='gist')
    op.drop_table('complaints_history')
    # ### end Alembic commands ###
