"""add unique to formname

Revision ID: 27511fd811f9
Revises: c68f261e2ed3
Create Date: 2026-02-26 10:21:50.114628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
# revision identifiers, used by Alembic.
revision: str = '27511fd811f9'
down_revision: Union[str, Sequence[str], None] = 'c68f261e2ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('meter_account')
    # op.drop_table('spatial_ref_sys')
    op.create_unique_constraint(None, 'form', ['form_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form', type_='unique')
    # ### end Alembic commands ###
