"""initial_migration

Revision ID: 368322f04e94
Revises: 
Create Date: 2026-02-26 09:05:37.338053
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
# revision identifiers, used by Alembic.
revision: str = '368322f04e94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # CREATE Technical Schema
    op.execute("CREATE SCHEMA IF NOT EXISTS technical_dep;")
    
    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('form',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('form_name', sa.Text(), nullable=False),
    sa.Column('form_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_meter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('times_tamped', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_accomplished', sa.Date(), nullable=False),
    sa.Column('consumer_name', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('pull_out_meter', sa.Text(), nullable=False),
    sa.Column('pull_out_meter_reading', sa.Integer(), nullable=False),
    sa.Column('new_meter_serial_no', sa.Text(), nullable=False),
    sa.Column('new_meter_brand', sa.Text(), nullable=False),
    sa.Column('meter_sealed', sa.Integer(), nullable=False),
    sa.Column('inital_reading', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('accomplished_by', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technical_dep'
    )
    op.create_index('idx_change_meter_geom', 'change_meter', ['geom'], unique=False, schema='technical_dep', postgresql_using='gist', if_not_exists=True)
    op.create_table('new_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('times_tamped', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_accomplished', sa.Date(), nullable=False),
    sa.Column('consumer_name', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('meter_serial_no', sa.Text(), nullable=False),
    sa.Column('meter_brand', sa.Text(), nullable=False),
    sa.Column('meter_sealed', sa.Integer(), nullable=False),
    sa.Column('inital_reading', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('accomplished_by', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technical_dep'
    )
    op.create_index('idx_new_connection_geom', 'new_connection', ['geom'], unique=False, schema='technical_dep', postgresql_using='gist', if_not_exists=True)
    op.create_table('change_meter_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_meter_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['change_meter_id'], ['technical_dep.change_meter.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technical_dep'
    )
    op.create_table('new_connection_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('new_connection_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['new_connection_id'], ['technical_dep.new_connection.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technical_dep'
    )
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('meter_account')
    op.create_unique_constraint(None, 'users_account', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_account', type_='unique')
    op.create_table('meter_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_no', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('consumer_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('consumer_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meter_location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mobile_no', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_account.id'], name=op.f('meter_account_user_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meter_account_pkey')),
    sa.UniqueConstraint('account_no', name=op.f('meter_account_account_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('new_connection_image', schema='technical_dep')
    op.drop_table('change_meter_image', schema='technical_dep')
    op.drop_index('idx_new_connection_geom', table_name='new_connection', schema='technical_dep', postgresql_using='gist')
    op.drop_table('new_connection', schema='technical_dep')
    op.drop_index('idx_change_meter_geom', table_name='change_meter', schema='technical_dep', postgresql_using='gist')
    op.drop_table('change_meter', schema='technical_dep')
    op.drop_table('form')
    op.drop_table('departments')
    # ### end Alembic commands ###
