"""initial_table_creation

Revision ID: 73c00c5bbaac
Revises: 
Create Date: 2026-02-26 21:12:20.185075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '73c00c5bbaac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.execute("CREATE SCHEMA IF NOT EXISTS technical_dep;")

    # ### Complaint Status Name Table
    op.create_table('complaints_status_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_name')
    )

    # ### Departments
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # ### Permissions
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )

    # ### Roles
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # ### Users Account
    op.create_table('users_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_name')
    )

    #  USER METER
    op.create_table('meter_account',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('account_no', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consumer_name', sa.Text(), nullable=False),
    sa.Column('consumer_type', sa.Text(), nullable=True),
    sa.Column('meter_location', sa.Text(), nullable=False),
    sa.Column('mobile_no', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, default=sa.func.now()),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    
    sa.ForeignKeyConstraint(['user_id'], ['users_account.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_no')
    )
    
    
    #  ### CONSUMERS COMPLAINTS
    op.create_table('consumer_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_pole', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('village', sa.Text(), nullable=False),
    sa.Column('municipality', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('timestamped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_account.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consumer_complaints_location', 'consumer_complaints', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
    
    # ### FORM
    op.create_table('form',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('form_name', sa.Text(), nullable=False),
    sa.Column('form_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_name')
    )

    # ### NEWS
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.Date(), nullable=False),
    sa.Column('time_posted', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_account.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### Roles Permissions
    op.create_table('roles_permission',
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perm_id'], ['permissions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roles_id', 'perm_id')
    )

    # ### User Roles
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_account.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )

    # ### Complaints Images
    op.create_table('complaints_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaints_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['complaints_id'], ['consumer_complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### Complaints Status
    op.create_table('complaints_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['consumer_complaints.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['complaints_status_name.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### Completed Complaint Images
    op.create_table('completed_complaint_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['consumer_complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # NEWS IMAGE 
    op.create_table('news_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### Change Meter
    op.create_table('change_meter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('timestamped', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_accomplished', sa.Date(), nullable=False),
    sa.Column('account_no', sa.Text(), nullable=True),
    sa.Column('consumer_name', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('pull_out_meter', sa.Text(), nullable=False),
    sa.Column('pull_out_meter_reading', sa.Integer(), nullable=False),
    sa.Column('new_meter_serial_no', sa.Text(), nullable=False),
    sa.Column('new_meter_brand', sa.Text(), nullable=False),
    sa.Column('meter_sealed', sa.Text(), nullable=False),
    sa.Column('initial_reading', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('accomplished_by', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technical_dep'
    )
    op.create_index('idx_change_meter_geom', 'change_meter', ['geom'], unique=False, schema='technical_dep', postgresql_using='gist', if_not_exists=True)

    # NEW CONNECTION
    op.create_table('new_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('times_tamped', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_accomplished', sa.Date(), nullable=False),
    sa.Column('account_no', sa.Text(), nullable=True),
    sa.Column('consumer_name', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('meter_serial_no', sa.Text(), nullable=False),
    sa.Column('meter_brand', sa.Text(), nullable=False),
    sa.Column('meter_sealed', sa.Integer(), nullable=False),
    sa.Column('inital_reading', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('accomplished_by', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technical_dep'
    )
    op.create_index('idx_new_connection_geom', 'new_connection', ['geom'], unique=False, schema='technical_dep', postgresql_using='gist', if_not_exists=True)

    # CHANGE METER IMAGES
    op.create_table('change_meter_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_meter_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['change_meter_id'], ['technical_dep.change_meter.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technical_dep'
    )

    # NEW CONNECTION IMAGES 
    op.create_table('new_connection_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('new_connection_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['new_connection_id'], ['technical_dep.new_connection.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='technical_dep'
    )


    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey')),
    if_not_exists=True
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_table('new_connection_image', schema='technical_dep', if_exists=True)
    op.drop_table('change_meter_image', schema='technical_dep', if_exists=True)
    op.drop_index('idx_new_connection_geom', table_name='new_connection', schema='technical_dep', postgresql_using='gist', if_exists=True)
    op.drop_table('new_connection', schema='technical_dep', if_exists=True)
    op.drop_index('idx_change_meter_geom', table_name='change_meter', schema='technical_dep', postgresql_using='gist', if_exists=True)
    op.drop_table('change_meter', schema='technical_dep', if_exists=True)
    op.drop_table('news_images', if_exists=True)
    op.drop_table('completed_complaint_image', if_exists=True)
    op.drop_table('complaints_status', if_exists=True)
    op.drop_table('complaints_images', if_exists=True)
    op.drop_table('user_roles', if_exists=True)
    op.drop_table('roles_permission',if_exists=True)
    op.drop_table('news', if_exists=True)
    op.drop_table('form', if_exists=True)
    op.drop_index('idx_consumer_complaints_location', table_name='consumer_complaints', postgresql_using='gist', if_exists=True)
    op.drop_table('consumer_complaints', if_exists=True)
    op.drop_table('roles', if_exists=True)
    op.drop_table('permissions', if_exists=True)
    op.drop_table('departments', if_exists=True)
    op.drop_table('complaints_status_name', if_exists=True)
    op.drop_table('meter_account', if_exists=True)
    op.drop_table('users_account', if_exists=True)
    # ### end Alembic commands ###
