"""consumers table

Revision ID: a6d6404f0ca6
Revises: a7d81f52a369
Create Date: 2026-03-09 16:02:58.360368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "a6d6404f0ca6"
down_revision: Union[str, Sequence[str], None] = "a7d81f52a369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consumer_meter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("account_no", sa.Text(), nullable=True),
        sa.Column("account_name", sa.Text(), nullable=True),
        sa.Column("account_type", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("meter_no", sa.Text(), nullable=True),
        sa.Column("meter_brand", sa.Text(), nullable=True),
        sa.Column("barcode", sa.Text(), nullable=True),
        sa.Column("date_installed", sa.Date(), nullable=True),
        sa.Column("village_id", sa.Integer(), nullable=False),
        sa.Column("municipality_id", sa.Integer(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["gis.municipality.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["village_id"], ["gis.villages.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_no"),
        schema="gis",
    )
    op.create_index(
        "idx_consumer_meter_geom",
        "consumer_meter",
        ["geom"],
        unique=False,
        schema="gis",
        postgresql_using="gist",
        if_not_exists=True,
    )
    
    op.create_index(
        "idx_consumer_meter_account_no_unique",
        "consumer_meter",
        ["account_no"],
        unique=True,
        schema="gis",
    )

    op.create_index(
        "idx_consumer_meter_account_no",
        "consumer_meter",
        ["account_no"],
        schema="gis",
        postgresql_using="gin",
        if_not_exists=True,
        postgresql_ops={"account_no": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_consumer_account_name",
        "consumer_meter",
        ["account_name"],
        schema="gis",
        postgresql_using="gin",
        if_not_exists=True,
        postgresql_ops={"account_name": "gin_trgm_ops"},
    )

    # TRIGGER

    op.execute(
        """
               CREATE OR REPLACE FUNCTION gis.consumer_meter_trigger_func() RETURNS TRIGGER AS $$
               DECLARE 
                   village integer;
                   municipal integer;
               BEGIN
                   SELECT b.village_id, b.municipality_id
                   INTO village, municipal
                   FROM gis.boundary as b
                   WHERE st_intersects(b.geom, new.geom)
                   LIMIT 1;
                   new.village_id = village;
                   new.municipality_id = municipal;
                   return new;
               END;
               $$ LANGUAGE plpgsql;
               """
    )

    op.execute(
        """
               CREATE TRIGGER consumer_meter_trigger
               BEFORE INSERT OR UPDATE
               ON gis.consumer_meter
               FOR EACH ROW EXECUTE PROCEDURE gis.consumer_meter_trigger_func();
               """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_consumer_meter_geom",
        table_name="consumer_meter",
        schema="gis",
        postgresql_using="gist",
        if_exists=True,
    )
    op.drop_index(
        "idx_consumer_meter_account_no_unique",
        table_name="consumer_meter",
        schema="gis",
        if_exists=True,
    )
    op.drop_index(
        "idx_consumer_meter_account_no",
        table_name="consumer_meter",
        schema="gis",
        postgresql_using="gin_trgm_ops",
        if_exists=True,
    )
    op.drop_index(
        "idx_consumer_account_name",
        table_name="consumer_meter",
        schema="gis",
        postgresql_using="gin_trgm_ops",
        if_exists=True,
    )
    op.drop_table("consumer_meter", schema="gis", if_exists=True)
    op.execute("DROP TRIGGER IF EXISTS consumer_meter_trigger ON gis.consumer_meter;")
    op.execute("DROP FUNCTION IF EXISTS gis.consumer_meter_trigger_func();")
    # ### end Alembic commands ###
