"""secondary_lines

Revision ID: a7d81f52a369
Revises: 1147df85f844
Create Date: 2026-03-09 09:23:11.125436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a7d81f52a369'
down_revision: Union[str, Sequence[str], None] = '1147df85f844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secondary_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('transformer_id', sa.Text(), nullable=True),
    sa.Column('secondary_line_id', sa.Text(), nullable=True),
    sa.Column('from_bus_id', sa.Text(), nullable=False),
    sa.Column('to_bus_id', sa.Text(), nullable=False),
    sa.Column('phasing', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('length_meters', sa.Numeric(precision=10, scale=4), sa.Computed('ST_Length(geom::geography)', persisted=True), nullable=True),
    sa.Column('conductor_type', sa.Integer(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_type'], ['gis.conductor_wires.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_bus_id'], ['gis.bus.bus_id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['gis.municipality.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_bus_id'], ['gis.bus.bus_id'], ),
    sa.ForeignKeyConstraint(['transformer_id'], ['gis.distribution_transformer.transformer_id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    
    sa.UniqueConstraint('secondary_line_id'),
    schema='gis'
    )
    op.create_index('idx_secondary_lines_geom', 'secondary_lines', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)
    
    
    # TRIGGER FUNCTION
    op.execute("""
    CREATE OR REPLACE FUNCTION gis.secondary_lines_trigger_func() RETURNS TRIGGER AS $$
    Declare
    transformer_id text;
    from_bus_id text;
    to_bus_id text;
    phasing text;
    village_id int;
    municipality_id int;
    secondary_line_id text;
    
    BEGIN
        IF EXISTS ( SELECT 1 FROM gis.transformer_linebushing as sl 
        WHERE ST_INTERSECTS(ST_ENDPOINT(sl.geom), ST_STARTPOINT(new.geom)))
        THEN
        SELECT dt.transformer_id, dt.to_secondary_bus_id, dt.secondary_phasing
        INTO transformer_id, from_bus_id, phasing
        FROM gis.bus as b
        join gis.distribution_transformer as dt on b.bus_id = dt.to_secondary_bus_id
        where st_intersects(b.geom, ST_STARTPOINT(new.geom))
        AND b.description = 'Secondary Node'
        LIMIT 1;
        ELSE
        SELECT sl.transformer_id, sl.to_bus_id, sl.phasing
        INTO transformer_id, from_bus_id, phasing
        FROM gis.bus as b
        join gis.secondary_lines as sl
        on b.bus_id = sl.to_bus_id
        where st_intersects(b.geom, ST_STARTPOINT(new.geom))
        AND b.description = 'Secondary Node'
        LIMIT 1;
        END IF;
        
        SELECT b.bus_id, 
        CASE WHEN new.description = 'OPEN-SECONDARY' THEN concat('O', b.bus_id) ELSE replace(b.bus_id, 'S', 'UB') END
        INTO to_bus_id, secondary_line_id
        FROM gis.bus as b
        where ST_INTERSECTS(b.geom, ST_ENDPOINT(new.geom))
        AND b.description = 'Secondary Node' 
        LIMIT 1; 
        
        SELECT b.village_id, b.municipality_id
        INTO village_id, municipality_id
        FROM gis.boundary as b
        WHERE st_intersects(b.geom, ST_ENDPOINT(new.geom))
        LIMIT 1;
        
    
        new.transformer_id = transformer_id;
        new.from_bus_id = from_bus_id;
        new.to_bus_id = to_bus_id;
        new.phasing = phasing;
        new.village_id = village_id;
        new.municipality_id = municipality_id;
        new.secondary_line_id = secondary_line_id;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
               CREATE TRIGGER secondary_lines_trigger
               BEFORE INSERT OR UPDATE
               ON gis.secondary_lines
               FOR EACH ROW EXECUTE FUNCTION gis.secondary_lines_trigger_func();
               """)
    
    op.execute("""
               CREATE OR REPLACE FUNCTION gis.secondary_lines_trigger_after_func()
               RETURNS TRIGGER AS $$
               begin
                    -- UPDATE GIS BUS OR NODE
                    UPDATE gis.bus as b
                    SET 
                    is_active = new.is_active
                    WHERE b.bus_id = new.to_bus_id
                    AND b.is_active is DISTINCT FROM new.is_active;
                    
                    
                    UPDATE gis.bus as b
                    SET 
                    substation_id = fb.substation_id,
                    feeder_id = fb.feeder_id
                    FROM gis.bus as fb 
                    where fb.bus_id = new.from_bus_id
                    AND b.bus_id = new.to_bus_id
                    AND (b.substation_id is DISTINCT FROM fb.substation_id or b.feeder_id is DISTINCT FROM fb.feeder_id);
                    
                RETURN NEW;
               end;
               $$ LANGUAGE plpgsql;
               """)
    op.execute("""
               CREATE TRIGGER secondary_lines_trigger_after
               AFTER INSERT OR UPDATE
               ON gis.secondary_lines
               FOR EACH ROW EXECUTE FUNCTION gis.secondary_lines_trigger_after_func();
               """)
    # ### end Alembic commands ###
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_secondary_lines_geom', table_name='secondary_lines', schema='gis', postgresql_using='gist', if_exists=True)
    op.drop_table('secondary_lines', schema='gis', if_exists=True)
    op.execute("DROP TRIGGER IF EXISTS secondary_lines_trigger ON gis.secondary_lines;")
    op.execute("DROP FUNCTION IF EXISTS gis.secondary_lines_trigger_func();")
    # ### end Alembic commands ###