"""create_franchise_area

Revision ID: c71825e4d3ca
Revises: bfa63f46ad01
Create Date: 2026-03-02 15:04:00.069537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2.functions import ST_Area
# revision identifiers, used by Alembic.
revision: str = 'c71825e4d3ca'
down_revision: Union[str, Sequence[str], None] = 'bfa63f46ad01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### CREATE GIS SCHEMA ###
    op.execute("CREATE SCHEMA IF NOT EXISTS gis;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False, unique=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['gis.municipality.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    op.create_table('boundary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('area', sa.BIGINT(), nullable=False, default=sa.func.ST_AREA("geom")),
    sa.ForeignKeyConstraint(['municipality_id'], ['gis.municipality.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    op.create_index('idx_boundary_geom', 'boundary', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_gis_boundary_geom'), 'boundary', ['geom'], unique=False, schema='gis')
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_boundary_geom'), table_name='boundary', schema='gis')
    op.drop_index('idx_boundary_geom', table_name='boundary', schema='gis', postgresql_using='gist')
    op.drop_table('boundary', schema='gis')
    op.drop_table('villages', schema='gis')
    op.drop_table('municipality', schema='gis')
    # ### end Alembic commands ###
