"""distribution_transformer_table and line_bushing

Revision ID: d0bff3d7567f
Revises: cb17179e0424
Create Date: 2026-03-05 16:26:18.069887

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bff3d7567f'
down_revision: Union[str, Sequence[str], None] = 'cb17179e0424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformer_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('kva_rating', sa.Text(), nullable=True),
    sa.Column('primary_voltage_rating', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('secondary_voltage_rating', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
  
    op.create_table('distribution_transformer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('transformer_id', sa.Text(), nullable=False),
    sa.Column('from_primary_bus_id', sa.Text(), nullable=True),
    sa.Column('primary_phasing', sa.Text(), nullable=True),
    sa.Column('to_secondary_bus_id', sa.Text(), nullable=True),
    sa.Column('secondary_phasing', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('installation_type', sa.Text(), nullable=True),
    sa.Column('connection_code', sa.Integer(), nullable=True),
    sa.Column('transformer_type', sa.Integer(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_primary_bus_id'], ['gis.bus.bus_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['gis.municipality.id'], ),
    sa.ForeignKeyConstraint(['to_secondary_bus_id'], ['gis.bus.bus_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transformer_type'], ['gis.transformer_type.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('to_secondary_bus_id'),
    sa.UniqueConstraint('transformer_id'),
    schema='gis'
    )
    op.create_index('idx_distribution_transformer_geom', 'distribution_transformer', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)
    
    op.create_table('transformer_linebushing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('conductor_type', sa.Integer(), nullable=True),
    sa.Column('transformer_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_type'], ['gis.conductor_wires.id'], ),
    sa.ForeignKeyConstraint(['transformer_id'], ['gis.distribution_transformer.transformer_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis'
    )
    op.create_index('idx_transformer_linebushing_geom', 'transformer_linebushing', ['geom'], unique=False, schema='gis', postgresql_using='gist',if_not_exists=True)
  
#  
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transformer_linebushing_geom', table_name='transformer_linebushing', schema='gis', postgresql_using='gist')
    
    op.drop_table('transformer_linebushing', schema='gis')
    
    op.drop_index('idx_distribution_transformer_geom', table_name='distribution_transformer', schema='gis', postgresql_using='gist')
    op.drop_table('distribution_transformer', schema='gis')
    op.drop_table('transformer_type', schema='gis')

    # ### end Alembic commands ###
