"""additional_gis_tables

Revision ID: fcb341c0761c
Revises: 675a539a210d
Create Date: 2026-03-03 22:35:10.841113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'fcb341c0761c'
down_revision: Union[str, Sequence[str], None] = '675a539a210d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # CONDUCTOR WIRES
    op.create_table('conductor_wires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='gis'
    )

    # CONSTRUCTION MATERIAL
    op.create_table('construction_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='gis'
    )

    # POLE CONSTRUCTION
    op.create_table('pole_construction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='gis'
    )

    # POLE ASSEMBLY SUCH AS A1, A2
    op.create_table('pole_assembly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['construction_id'], ['gis.pole_construction.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='gis'
    )
    
    # ELECTRIC POLES
    op.create_table('electric_poles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('pole_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipal_id', sa.Integer(), nullable=False),
    sa.Column('pole_assembly', sa.Text(), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['municipal_id'], ['gis.municipality.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pole_assembly'], ['gis.pole_assembly.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pole_id'),
    schema='gis'
    )
    op.create_index('idx_electric_poles_geom', 'electric_poles', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)

    # SUBSTATIONS
    op.create_table('substation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('substation_id', sa.Text(), nullable=False),
    sa.Column('phasing', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('generator_type', sa.Text(), nullable=True),
    sa.Column('voltage_rating_kv', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('voltage_profile_id', sa.Text(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipal_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['municipal_id'], ['gis.municipality.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('substation_id'),
    schema='gis'
    )
    op.create_index('idx_substation_geom', 'substation', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)

    # BUS
    op.create_table('bus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('pole_id', sa.Integer(), nullable=True),
    sa.Column('bus_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nominal_voltage_kv', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipal_id', sa.Integer(), nullable=False),
    sa.Column('substation_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['municipal_id'], ['gis.municipality.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pole_id'], ['gis.electric_poles.id'], ),
    sa.ForeignKeyConstraint(['substation_id'], ['gis.substation.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_id'),
    schema='gis'
    )
    op.create_index('idx_bus_geom', 'bus', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)

    # POLE MATERIAL
    op.create_table('pole_material',
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['gis.construction_material.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pole_id'], ['gis.electric_poles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pole_id', 'material_id'),
    schema='gis'
    )

    # FEEDER
    op.create_table('feeder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Text(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('feeder_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipal_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['gis.bus.bus_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipal_id'], ['gis.municipality.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_id'),
    sa.UniqueConstraint('feeder_id'),
    schema='gis'
    )
    op.create_index('idx_feeder_geom', 'feeder', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)

    # PRIMARY LINE
    op.create_table('primary_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('substation_id', sa.Integer(), nullable=False),
    sa.Column('feeder_id', sa.Text(), nullable=True),
    sa.Column('primary_line_id', sa.Text(), nullable=False),
    sa.Column('from_bus_id', sa.Text(), nullable=False),
    sa.Column('to_bus_id', sa.Text(), nullable=False),
    sa.Column('phasing', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_ground_type', sa.Text(), nullable=True),
    sa.Column('length_meters', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('conductor_wire', sa.Integer(), nullable=False),
    sa.Column('neutral_wire', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_wire'], ['gis.conductor_wires.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feeder_id'], ['gis.feeder.feeder_id'], ),
    sa.ForeignKeyConstraint(['from_bus_id'], ['gis.bus.bus_id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['gis.municipality.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['neutral_wire'], ['gis.conductor_wires.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substation_id'], ['gis.substation.id'], ),
    sa.ForeignKeyConstraint(['to_bus_id'], ['gis.bus.bus_id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['gis.villages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_line_id'),
    schema='gis'
    )
    op.create_index('idx_primary_lines_geom', 'primary_lines', ['geom'], unique=False, schema='gis', postgresql_using='gist', if_not_exists=True)


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_primary_lines_geom', table_name='primary_lines', schema='gis', postgresql_using='gist')
    op.drop_table('primary_lines', schema='gis')
    op.drop_index('idx_feeder_geom', table_name='feeder', schema='gis', postgresql_using='gist')
    op.drop_table('feeder', schema='gis')

    op.drop_table('pole_material', schema='gis')
    op.drop_index('idx_bus_geom', table_name='bus', schema='gis', postgresql_using='gist')
    op.drop_table('bus', schema='gis')



    op.drop_index('idx_substation_geom', table_name='substation', schema='gis', postgresql_using='gist')
    op.drop_table('substation', schema='gis')


    op.drop_index('idx_electric_poles_geom', table_name='electric_poles', schema='gis', postgresql_using='gist')
    op.drop_table('electric_poles', schema='gis')


    op.drop_table('pole_assembly', schema='gis')
    op.drop_table('pole_construction', schema='gis')
    op.drop_table('construction_material', schema='gis')
    op.drop_table('conductor_wires', schema='gis')
    # ### end Alembic commands ###
